steps:
  - name: 'gcr.io/cloud-builders/yarn'
    env: &env
      - 'NODE_ENV=$_NODE_ENV'
  - name: node:15
    entrypoint: yarn
    args: ["install"]
  - name: node:15
    entrypoint: yarn
    args: ["build"]
    env: *env
  - name: gcr.io/cloud-builders/gcloud
    args:
      - "app"
      - "deploy"
      - "app.yaml"
      - "--project=$PROJECT_ID"
      - "--quiet"
